name: Wakatime

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * */2"

jobs:
  update-readme:
    name: Wakatime statistics
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Update monthly statistics
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SECTION_NAME: wakamonthly
          COMMIT_MESSAGE: Update monthly Wakatime statistics
          TIME_RANGE: last_30_days
          LANG_COUNT: 4
          BLOCKS: ░█

      - name: Update yearly statistics
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SECTION_NAME: wakayearly
          COMMIT_MESSAGE: Update yearly Wakatime statistics
          TIME_RANGE: last_year
          LANG_COUNT: 6
          BLOCKS: ░█
